Add services parent to subsite views #148
localgovdrupal/localgov_subsites pull request #151
Opened 2024-05-31 09:09 UTC by stephen-cox

Adds a parent page field to subsite overview pages. When this is used the subsite will appear in the services heirachy.

![image](https://github.com/localgovdrupal/localgov_subsites/assets/7189914/a8e09ca0-3686-4490-9c26-cec0f79751b0)

Fixes #148

2024-06-03 15:21 UTC, willguv commented
The screenshot looks fine @stephen-cox - thanks for working on it

Don't think I've got the power to merge this PR though :)

2024-06-04 07:11 UTC, stephen-cox commented
> Don't think I've got the power to merge this PR though :)

Thanks for checking @willguv - we'll merge and release later at Merge Tuesday

2024-06-04 11:43 UTC, finnlewis commented
Discussing in Merge Tuesday: 
 - Ekes points out that we have other fields that could be parent pages, and we might want to mention that this is a services parent page. For example, if posting into directories a directory might be a parent. 
 - Ru concurs. Working in subsites, people refer to parent pages to mean the subsite overview, but also the services parent page.

Q1: Should we name this "Service parent page" ?

Q2. What is the expected behaviour of setting this field? 
 - By selecting a parent service landing page or service sub-landing page:
 -  - 1. it sets the url alias to be child of the parent, which in turn sets the breadcrumb.
 -  - 2. It then gets listed as a potential child in service landing pages. 
 
Also noting that this is just for new installs for now, so do we need documentation on how to implement on existing sites? 

See https://github.com/localgovdrupal/localgov_guides/pull/166

I think I need to read up on th original issue https://github.com/localgovdrupal/localgov/issues/487 

I'll do that this week.

2024-06-05 14:22 UTC, willguv commented
Thanks for these questions @finnlewis 

Q1

I discussed naming of parent fields with content designers when we were rationalising them a while ago. "Parent page" was decided upon. 

Presumably a content designer would only set a parent page that would make sense, and we only allow parent fields to be set that make sense. So does this field name need to be anything other than "Parent page"? 

Sorry if I'm missing something here.

Q2

The expected behavior is as you describe. It's valid that subsite overview pages are listed in service landing pages as potential children, and I've seen content designers try to do this.

Is there a risk in adding this to all new sites, not just new installs? Most councils are likely to use it and can ignore if not. If there's a risk, agree a doc is the right way to go.

2024-06-17 13:47 UTC, ekes requested changes

2024-06-17 13:47 UTC, ekes commented on localgov_subsites.install
> +function localgov_subsites_install() {
As we're going to be altering config here I think we want a `$is_syncing` here and check that it's not before updating the config.

2024-06-17 13:47 UTC, ekes commented on config/install/field.field.node.localgov_subsites_page.localgov_subsites_parent.yml
> +label: 'Subsite parent page'
:smile:

2024-06-18 09:46 UTC, stephen-cox commented on localgov_subsites.install
> +function localgov_subsites_install() {
Indeed it should. Just added a check for this.

2024-06-18 09:55 UTC, ekes approved these changes

2024-06-18 11:20 UTC, merged